name: taxiconnect
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  file_picker: ^8.0.0+1
  http: ^1.2.0
  path_provider: ^2.1.2
  responsive_sizer: ^3.3.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  bloc: ^8.1.4
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  uuid: ^4.4.0
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.5
  network_image: ^0.1.1
  get_it: ^7.6.7
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.0
  fl_country_code_picker: ^0.0.4
  pinput: ^4.0.0
  google_maps_flutter: ^2.5.3
  equatable: ^2.0.5
  location: ^6.0.1
  sms_autofill: ^2.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons
    - assets/icons/png
    - assets/icons/svg
    - assets/images
    - assets/images/png
    - assets/images/svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
